analyzer:
  errors:
    invalid_annotation_target: ignore
    unnecessary_non_null_assertion: ignore
  exclude:
    - test/**.dart
linter:
  rules:
    - empty_constructor_bodies
    - library_private_types_in_public_api
    - use_rethrow_when_possible
    - unnecessary_brace_in_string_interps
    - unnecessary_string_interpolations
    - avoid_init_to_null
    - constant_identifier_names
    - await_only_futures
    - use_build_context_synchronously
    - avoid_unnecessary_containers
    - prefer_function_declarations_over_variables
    - prefer_is_empty
    - prefer_interpolation_to_compose_strings
    - camel_case_extensions
    - prefer_const_constructors
    - prefer_const_declarations
    - unnecessary_const
    - prefer_collection_literals
    - camel_case_types